param(
    [Parameter(Mandatory)][string]$RepositoryRoot,
    [string]$GitHubCommand = 'gh',
    [string]$AzureCommand = 'az',
    [string]$JFrogCommand = 'jf'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Test-CommandAvailable([string]$Command) { return $null -ne (Get-Command $Command -ErrorAction SilentlyContinue) }
function Invoke-NativeCommand {
    param([string]$Command,[string[]]$Arguments,[string]$WorkingDirectory,[int[]]$AcceptedExitCodes=@(0),[switch]$Json)
    $previousExit=$global:LASTEXITCODE
    try {
        Push-Location $WorkingDirectory
        try { $raw=& $Command @Arguments 2>$null; $exitCode=$LASTEXITCODE } finally { Pop-Location }
        $text=($raw -join "`n").Trim(); $accepted=$AcceptedExitCodes -contains $exitCode; $data=$null; $parseError=$false
        if ($accepted -and $Json -and -not [string]::IsNullOrWhiteSpace($text)) { try { $data=$text | ConvertFrom-Json } catch { $parseError=$true; $accepted=$false } }
        elseif ($accepted -and -not $Json) { $data=$text }
        [pscustomobject]@{ok=$accepted;data=$data;exitCode=$exitCode;parseError=$parseError}
    } catch { [pscustomobject]@{ok=$false;data=$null;exitCode=$null;parseError=$false} } finally { $global:LASTEXITCODE=$previousExit }
}
function Get-PropertyValue { param($Object,[string]$Name); if($null -eq $Object){return $null}; $p=$Object.PSObject.Properties[$Name]; if($null -eq $p){return $null}; $p.Value }
function Convert-AzureRun {
    param($Run,[string]$HeadSha); $definition=Get-PropertyValue $Run 'definition'; $sourceVersion=[string](Get-PropertyValue $Run 'sourceVersion')
    [pscustomobject]@{id=Get-PropertyValue $Run 'id';buildNumber=Get-PropertyValue $Run 'buildNumber';pipelineId=Get-PropertyValue $definition 'id';pipelineName=Get-PropertyValue $definition 'name';status=Get-PropertyValue $Run 'status';result=Get-PropertyValue $Run 'result';sourceBranch=Get-PropertyValue $Run 'sourceBranch';sourceVersion=$sourceVersion;queueTime=Get-PropertyValue $Run 'queueTime';startTime=Get-PropertyValue $Run 'startTime';finishTime=Get-PropertyValue $Run 'finishTime';exactHead=(-not [string]::IsNullOrWhiteSpace($HeadSha) -and $sourceVersion -eq $HeadSha)}
}
$root=(Resolve-Path $RepositoryRoot).Path; $output=Join-Path $root '.security/output'; New-Item -ItemType Directory -Force -Path $output | Out-Null
$branchRaw=((git -C $root rev-parse --abbrev-ref HEAD 2>$null)-join '').Trim(); $headSha=((git -C $root rev-parse HEAD 2>$null)-join '').Trim(); $origin=((git -C $root config --get remote.origin.url 2>$null)-join '').Trim(); $detached=$branchRaw -eq 'HEAD' -or [string]::IsNullOrWhiteSpace($branchRaw); $branch=$(if($detached){$null}else{$branchRaw})
$changedFiles=@((git -C $root status --porcelain=v1 --untracked-files=all 2>$null)|ForEach-Object{if($_.Length -gt 3){$_.Substring(3)}}|Where-Object{-not [string]::IsNullOrWhiteSpace($_)}); $worktreeDirty=$changedFiles.Count -gt 0
$configPath=Join-Path $root '.security/build-intelligence.json'; $config=$null; if(Test-Path $configPath){try{$config=Get-Content $configPath -Raw|ConvertFrom-Json}catch{throw "Invalid build intelligence config: $configPath"}}
$github=[ordered]@{status='unavailable';correlation='none';runs=@();pr=$null;checks=@();errors=@()}; $azure=[ordered]@{status='unavailable';correlation='none';runs=@();errors=@()}; $jfrog=[ordered]@{status='unavailable';builds=@();errors=@()}
if(Test-CommandAvailable $GitHubCommand){$auth=Invoke-NativeCommand $GitHubCommand @('auth','status') $root;if($auth.ok){$github.status='available';$fields='databaseId,number,name,workflowName,status,conclusion,headBranch,headSha,event,createdAt,updatedAt,url';if($headSha){$exact=Invoke-NativeCommand $GitHubCommand @('run','list','--commit',$headSha,'--limit','10','--json',$fields) $root @(0) -Json;if($exact.ok){$github.runs=@($exact.data);if($github.runs.Count){$github.correlation='exact-head'}}else{$github.errors+=@([pscustomobject]@{operation='runs-by-commit';exitCode=$exact.exitCode;parseError=$exact.parseError})}};if($github.runs.Count -eq 0 -and $branch){$byBranch=Invoke-NativeCommand $GitHubCommand @('run','list','--branch',$branch,'--limit','10','--json',$fields) $root @(0) -Json;if($byBranch.ok){$github.runs=@($byBranch.data);if($github.runs.Count){$github.correlation='branch'}}else{$github.errors+=@([pscustomobject]@{operation='runs-by-branch';exitCode=$byBranch.exitCode;parseError=$byBranch.parseError})}};if($branch){$pr=Invoke-NativeCommand $GitHubCommand @('pr','view',$branch,'--json','number,title,url,headRefName,headRefOid,baseRefName,isDraft,state') $root @(0) -Json;if($pr.ok -and $pr.data){$github.pr=$pr.data;$checks=Invoke-NativeCommand $GitHubCommand @('pr','checks',$branch,'--json','bucket,completedAt,description,event,link,name,startedAt,state,workflow') $root @(0,8) -Json;if($checks.ok){$github.checks=@($checks.data)}else{$github.errors+=@([pscustomobject]@{operation='pr-checks';exitCode=$checks.exitCode;parseError=$checks.parseError})}}elseif($pr.exitCode -notin @(0,1)){$github.errors+=@([pscustomobject]@{operation='pr-view';exitCode=$pr.exitCode;parseError=$pr.parseError})}};if($github.errors.Count -gt 0 -and $github.runs.Count -eq 0 -and $null -eq $github.pr){$github.status='query-failed'}}else{$github.status='not-authenticated'}}
if(Test-CommandAvailable $AzureCommand){$extension=Invoke-NativeCommand $AzureCommand @('extension','show','--name','azure-devops','--output','json','--only-show-errors') $root @(0) -Json;if(-not $extension.ok){$azure.status='extension-unavailable'}elseif($detached){$azure.status='no-branch'}else{$azureConfig=$(if($config){Get-PropertyValue $config 'azure'}else{$null});$originLooksAzure=$origin -match '(dev\.azure\.com|visualstudio\.com)';if($null -eq $azureConfig -and -not $originLooksAzure){$azure.status='not-configured'}else{$args=@('pipelines','runs','list','--branch',$branch,'--top','10','--query-order','QueueTimeDesc','--output','json','--only-show-errors');if($azureConfig){$organization=Get-PropertyValue $azureConfig 'organization';$project=Get-PropertyValue $azureConfig 'project';$pipelineIds=@(Get-PropertyValue $azureConfig 'pipelineIds');if($organization){$args+=@('--organization',[string]$organization)};if($project){$args+=@('--project',[string]$project)};if($pipelineIds.Count -gt 0 -and $null -ne $pipelineIds[0]){$args+='--pipeline-ids';foreach($id in $pipelineIds){$args+=[string]$id}};if(-not $organization -and -not $project){$args+=@('--detect','true')}}else{$args+=@('--detect','true')};$runsResult=Invoke-NativeCommand $AzureCommand $args $root @(0) -Json;if($runsResult.ok){$azure.status='available';$azure.runs=@($runsResult.data|ForEach-Object{Convert-AzureRun $_ $headSha});if(@($azure.runs|Where-Object{$_.exactHead}).Count){$azure.correlation='exact-head'}elseif($azure.runs.Count){$azure.correlation='branch'}}else{$azure.status='query-failed';$azure.errors+=@([pscustomobject]@{operation='pipeline-runs';exitCode=$runsResult.exitCode;parseError=$runsResult.parseError})}}}}
if(Test-CommandAvailable $JFrogCommand){$jfrog.status='not-resolved';$jfrogConfig=$(if($config){Get-PropertyValue $config 'jfrog'}else{$null});$buildName=$(if($jfrogConfig){Get-PropertyValue $jfrogConfig 'buildName'}else{$null});if($buildName){$buildNumber=$null;$source=[string](Get-PropertyValue $jfrogConfig 'buildNumberFrom');if($source -eq 'githubRunNumber' -and $github.runs.Count){$buildNumber=[string]$github.runs[0].number}elseif($source -eq 'githubRunId' -and $github.runs.Count){$buildNumber=[string]$github.runs[0].databaseId}elseif($source -eq 'azureBuildId' -and $azure.runs.Count){$c=@($azure.runs|Where-Object{$_.exactHead});if(!$c.Count){$c=@($azure.runs)};if($c.Count){$buildNumber=[string]$c[0].id}}elseif($source -eq 'azureBuildNumber' -and $azure.runs.Count){$c=@($azure.runs|Where-Object{$_.exactHead});if(!$c.Count){$c=@($azure.runs)};if($c.Count){$buildNumber=[string]$c[0].buildNumber}};$fixed=Get-PropertyValue $jfrogConfig 'buildNumber';if([string]::IsNullOrWhiteSpace($buildNumber) -and $fixed){$buildNumber=[string]$fixed;$source='configured'};if($buildNumber){$scanArgs=@('build-scan',[string]$buildName,$buildNumber,'--format=json','--vuln');$serverId=Get-PropertyValue $jfrogConfig 'serverId';$project=Get-PropertyValue $jfrogConfig 'project';if($serverId){$scanArgs+=@('--server-id',[string]$serverId)};if($project){$scanArgs+=@('--project',[string]$project)};$scan=Invoke-NativeCommand $JFrogCommand $scanArgs $root @(0,3) -Json;$evidenceFile=$null;if($scan.ok -and $scan.data){$evidencePath=Join-Path $output 'jfrog-build-scan.json';$scan.data|ConvertTo-Json -Depth 30|Set-Content $evidencePath;$evidenceFile='.security/output/jfrog-build-scan.json'};if($scan.ok){$jfrog.status='available'}else{$jfrog.status='query-failed';$jfrog.errors+=@([pscustomobject]@{operation='build-scan';exitCode=$scan.exitCode;parseError=$scan.parseError})};$jfrog.builds=@([pscustomobject]@{name=[string]$buildName;number=$buildNumber;source=$source;scanStatus=$(if(-not $scan.ok){'failed'}elseif($scan.exitCode -eq 3){'policy-violation'}else{'completed'});exitCode=$scan.exitCode;evidenceFile=$evidenceFile})}}}
$result=[ordered]@{schema=2;collectedAt=(Get-Date).ToUniversalTime().ToString('o');git=[ordered]@{repositoryRoot='.';branch=$branch;headSha=$headSha;detached=$detached;origin=$origin;changedFiles=$changedFiles;worktreeDirty=$worktreeDirty;remoteBuildScope=$(if($worktreeDirty){'committed-head-only'}else{'head-and-worktree'})};providers=[ordered]@{github=$github;azure=$azure;jfrog=$jfrog}}
$path=Join-Path $output 'build-context.json';$result|ConvertTo-Json -Depth 15|Set-Content $path;$result
